=== ridernator/messageGenerator/tools/MessageGenerator/config/Structure.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="simpleType">
        <xs:annotation>
            <xs:documentation>Enumeration of the different simple types (ints , floats)</xs:documentation>
        </xs:annotation>
        
        <xs:restriction base="xs:string">
            <xs:enumeration value="unsigned_int_8">
                <xs:annotation>
                    <xs:documentation>Unsigned 8-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="unsigned_int_16">
                <xs:annotation>
                    <xs:documentation>Unsigned 16-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="unsigned_int_32">
                <xs:annotation>
                    <xs:documentation>Unsigned 32-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="unsigned_int_64">
                <xs:annotation>
                    <xs:documentation>Unsigned 64-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="int_8">
                <xs:annotation>
                    <xs:documentation>Signed 8-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="int_16">
                <xs:annotation>
                    <xs:documentation>Signed 16-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="int_32">
                <xs:annotation>
                    <xs:documentation>Signed 32-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="int_64">
                <xs:annotation>
                    <xs:documentation>Signed 64-bit integer</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="float_32">
                <xs:annotation>
                    <xs:documentation>32-bit floating point number</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            
            <xs:enumeration value="float_64">                
                <xs:annotation>                    
                    <xs:documentation>64-bit floating point number</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="string">                
                <xs:annotation>                    
                    <xs:documentation>String type</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="extendedType">
        <xs:annotation>
            <xs:documentation>Enumeration of the extended types (Array, Sequence etc)</xs:documentation>
        </xs:annotation>
            
        <xs:restriction base="xs:string">
            <xs:enumeration value="complex_unsigned_int_8">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 8-bit unsigned integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_unsigned_int_16">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 16-bit unsigned integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_unsigned_int_32">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 32-bit unsigned integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_unsigned_int_64">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 64-bit unsigned integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_int_8">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 8-bit signed integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_int_16">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 16-bit signed integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_int_32">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 32-bit signed integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_int_64">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 64-bit signed integers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_float_32">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 32-bit floating point numbers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="complex_float_64">                
                <xs:annotation>                    
                    <xs:documentation>Complex number comprised of two 64-bit floating point numbers</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="array">                
                <xs:annotation>                    
                    <xs:documentation>Array type. Use arraySize field to set array size and subType field to set array element type</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="sequence">                
                <xs:annotation>                    
                    <xs:documentation>Sequence type. Use subElement field to set sequence element type</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="map">                
                <xs:annotation>                    
                    <xs:documentation>Map type. Use subElement and subElement2 fields to set map key and value type</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
            
            <xs:enumeration value="structure">                
                <xs:annotation>                    
                    <xs:documentation>Structure type. Type is another custom structure</xs:documentation>                
                </xs:annotation>            
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="type">
        <xs:annotation>
            <xs:documentation>All types (Union of simpleType and extendedType)</xs:documentation>
        </xs:annotation>
        
        <xs:union memberTypes="simpleType extendedType"/>
    </xs:simpleType>

    <xs:complexType name="constant">
        <xs:annotation>
            <xs:documentation>Definition of a constant in a structure</xs:documentation>
        </xs:annotation>
        
        <xs:all>
            <xs:element name="documentation" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>Documentation for this constant Will be added to generated source files></xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>        
            
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The name of this constant</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        
        <xs:attribute name="type" type="simpleType" use="required">
            <xs:annotation>
                <xs:documentation>The type of this constant</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        
        <xs:attribute name="value" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The value of this constant</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="element">
        <xs:annotation>
            <xs:documentation>Definition of an element in a structure</xs:documentation>
        </xs:annotation>
        
        <xs:all>
            <xs:element name="documentation" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>Documentation for this element. Will be added to generated source files></xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="subElement" type="element" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>If the type of this element is array or sequence then this refers to the type of elements in the array or sequence. If the type is map then this refers to the type of the keys of the map</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="subElement2" type="element" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>If the type is map then this refers to the type of the values of the map</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>        
            
        <xs:attribute name="name" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>The name of this element</xs:documentation>
            </xs:annotation>
        </xs:attribute>
            
        <xs:attribute name="arraySize" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>The size of the array (If this is an array type)</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        
        <xs:attribute name="type" type="type" use="required">
            <xs:annotation>
                <xs:documentation>The type of this element</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        
        <xs:attribute name="structureName" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>If the type of this element is "structure" then this is the structure's name</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="constants">
        <xs:annotation>
            <xs:documentation>Constants in this structure</xs:documentation>
        </xs:annotation>
        
        <xs:sequence>
            <xs:element name="constant" type="constant" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>A constant value placed in the structure</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="elements">
        <xs:annotation>
            <xs:documentation>Elements in this structure</xs:documentation>
        </xs:annotation>
        
        <xs:sequence>
            <xs:element name="element" type="element" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>An element which makes up part of this structure</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="structure">
        <xs:annotation>
            <xs:documentation>Definition of a structure and all its elements</xs:documentation>
        </xs:annotation>
        
        <xs:complexType>
            <xs:sequence>
                <xs:element name="documentation" type="xs:string" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Documentation for this structure. Will be added to generated source files</xs:documentation>
                    </xs:annotation>
                </xs:element>
                
                <xs:element name="constants" type="constants" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Constants placed in the structure</xs:documentation>
                    </xs:annotation>
                </xs:element>
                
                <xs:element name="elements" type="elements" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Elements which make up part of this structure</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            
            <xs:attribute name="name" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>The name of this structure</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element> 
</xs:schema>

=== ridernator/messageGenerator/tools/MessageGenerator/config/blob.xml
<?xml version="1.0" encoding="UTF-8"?>

<structure name="Blob" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Structure.xsd">
    <documentation>This class is the blob class</documentation>
    
    <constants>
		<constant name="SIZE_OF_ARRAY" type="unsigned_int_32" value="10000">
			<documentation>Size of the "intArray" array</documentation>
		</constant>
    </constants>
      
    <elements>  
        <element name="fatArray" type="array" arraySize="SIZE_OF_ARRAY">
            <documentation>This type is called fatArray</documentation>
            <subElement type="float_64"/>
        </element>
    </elements>
</structure>

=== ridernator/messageGenerator/tools/MessageGenerator/config/stressTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<structure name="StressTest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Structure.xsd">
    <documentation>This class is the stress test class</documentation>
    
    <constants>
		<constant name="SIZE_OF_INT_ARRAY" type="int_32" value="10">
			<documentation>Size of the "intArray" array</documentation>
		</constant>
    </constants>
      
    <elements>  
        <element name="simpleInt" type="int_32">
            <documentation>This type is called simpleInt</documentation>
        </element>
        
        <element name="simpleIntNoDoc" type="int_32" />
    
        <element name="simpleFloat" type="float_32">
            <documentation>This type is called simpleFloat</documentation>
        </element>
    
        <element name="intArray" type="array" arraySize="SIZE_OF_INT_ARRAY">
            <documentation>This type is called intArray</documentation>
            <subElement type="int_32" />
        </element>
    
        <element name="floatSequence" type="sequence">
            <documentation>This type is called floatSequence</documentation>
            <subElement type="float_32" />
        </element>
    
        <element name="arrayOfIntSequences" type="array" arraySize="10">
            <documentation>This type is called arrayOfIntSequences</documentation>
            <subElement type="sequence">
                <subElement type="int_32" />
            </subElement>
        </element>
    
        <element name="sequenceOfIntArrays" type="sequence">
            <documentation>This type is called arrayOfIntSequences</documentation>
            <subElement type="array" arraySize="10">
                <subElement type="int_32" />
            </subElement>
        </element>
    
        <element name="intToDoubleMap" type="map">
            <subElement type="int_32" />
            <subElement2 type="float_64" />
        </element>
    
        <element name="intArray5d" type="array" arraySize="2">
            <documentation>This type is called intArray5d</documentation>
            <subElement type="array" arraySize="3">
                <subElement type="array" arraySize="4">
                    <subElement type="array" arraySize="5">
                        <subElement type="array" arraySize="6">
                            <subElement type="int_32" />
                        </subElement>
                    </subElement>
                </subElement>
            </subElement>
        </element>
    
        <element name="floatSequence5d" type="sequence">
            <documentation>This type is called floatSequence5d</documentation>
            <subElement type="sequence">
                <subElement type="sequence">
                    <subElement type="sequence">
                        <subElement type="sequence">
                            <subElement type="float_32" />
                        </subElement>
                    </subElement>
                </subElement>
            </subElement>
        </element>
		
        <element name="blobSequence5d" type="sequence">
            <documentation>This type is called floatSequence5d</documentation>
            <subElement type="sequence">
                <subElement type="sequence">
                    <subElement type="sequence">
                        <subElement type="sequence">
                            <subElement type="structure" structureName="Blob" />
                        </subElement>
                    </subElement>
                </subElement>
            </subElement>
        </element>
    </elements>
</structure>
